/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_salvador_macias;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Apple
 */
public class notepadPlus extends javax.swing.JFrame {

    /**
     * Creates new form notepadPlus
     */
    public notepadPlus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        dialog_size = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txt_size = new javax.swing.JTextField();
        btn_actualizar = new javax.swing.JButton();
        dialog_estilo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jcb_estilo = new javax.swing.JComboBox<>();
        dialog_colorTxt = new javax.swing.JDialog();
        btn_colorTxt = new javax.swing.JButton();
        dialog_ColorFondo = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        boton_nuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        boton_salir = new javax.swing.JMenuItem();
        menu_formato = new javax.swing.JMenu();
        menu_fuente = new javax.swing.JMenuItem();
        menu_tamano = new javax.swing.JMenuItem();
        menu_estilo = new javax.swing.JMenuItem();
        menu_colorTexto = new javax.swing.JMenuItem();
        menu_colorFondo = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Notepad+ - Creado por Salvador Macias");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jLabel2.setText("Ingrese el tamano");

        btn_actualizar.setText("actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_sizeLayout = new javax.swing.GroupLayout(dialog_size.getContentPane());
        dialog_size.getContentPane().setLayout(dialog_sizeLayout);
        dialog_sizeLayout.setHorizontalGroup(
            dialog_sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_sizeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(dialog_sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualizar)
                    .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        dialog_sizeLayout.setVerticalGroup(
            dialog_sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_sizeLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(dialog_sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btn_actualizar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel3.setText("Estilo");

        jcb_estilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plano", "Negrita", "Italica" }));
        jcb_estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_estiloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_estiloLayout = new javax.swing.GroupLayout(dialog_estilo.getContentPane());
        dialog_estilo.getContentPane().setLayout(dialog_estiloLayout);
        dialog_estiloLayout.setHorizontalGroup(
            dialog_estiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_estiloLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jcb_estilo, 0, 199, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        dialog_estiloLayout.setVerticalGroup(
            dialog_estiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_estiloLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(dialog_estiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcb_estilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        btn_colorTxt.setText("seleccione el color");
        btn_colorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_colorTxtLayout = new javax.swing.GroupLayout(dialog_colorTxt.getContentPane());
        dialog_colorTxt.getContentPane().setLayout(dialog_colorTxtLayout);
        dialog_colorTxtLayout.setHorizontalGroup(
            dialog_colorTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_colorTxtLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btn_colorTxt)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        dialog_colorTxtLayout.setVerticalGroup(
            dialog_colorTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_colorTxtLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btn_colorTxt)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialog_ColorFondoLayout = new javax.swing.GroupLayout(dialog_ColorFondo.getContentPane());
        dialog_ColorFondo.getContentPane().setLayout(dialog_ColorFondoLayout);
        dialog_ColorFondoLayout.setHorizontalGroup(
            dialog_ColorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialog_ColorFondoLayout.setVerticalGroup(
            dialog_ColorFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        menu_archivo.setText("Archivo");

        boton_nuevo.setText("nuevo");
        boton_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_nuevoMouseClicked(evt);
            }
        });
        boton_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nuevoActionPerformed(evt);
            }
        });
        menu_archivo.add(boton_nuevo);
        menu_archivo.add(jSeparator1);

        boton_salir.setText("salir");
        boton_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_salirMouseClicked(evt);
            }
        });
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(boton_salir);

        jMenuBar1.add(menu_archivo);

        menu_formato.setText("Formato");

        menu_fuente.setText("cambiar fuente");
        menu_fuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fuenteActionPerformed(evt);
            }
        });
        menu_formato.add(menu_fuente);

        menu_tamano.setText("cambiar tamano");
        menu_tamano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_tamanoMouseClicked(evt);
            }
        });
        menu_tamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tamanoActionPerformed(evt);
            }
        });
        menu_formato.add(menu_tamano);

        menu_estilo.setText("cambiar estilo");
        menu_estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_estiloActionPerformed(evt);
            }
        });
        menu_formato.add(menu_estilo);

        menu_colorTexto.setText("color de texto");
        menu_colorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_colorTextoActionPerformed(evt);
            }
        });
        menu_formato.add(menu_colorTexto);

        menu_colorFondo.setText("color de fondo");
        menu_colorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_colorFondoActionPerformed(evt);
            }
        });
        menu_formato.add(menu_colorFondo);

        jMenuBar1.add(menu_formato);

        Ayuda.setText("ayuda");
        Ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyudaMouseClicked
        jDialog1.setVisible(true);
        jDialog1.pack();
        // TODO add your handling code here:
    }//GEN-LAST:event_AyudaMouseClicked

    private void boton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nuevoActionPerformed
        // System.out.println("pepe");
        jTextArea1.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_nuevoActionPerformed

    private void boton_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nuevoMouseClicked
        System.out.println("pepe");
        jTextArea1.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_nuevoMouseClicked

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        this.setVisible(false);
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_salirActionPerformed

    private void boton_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_salirMouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_salirMouseClicked

    private void menu_fuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fuenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_fuenteActionPerformed

    private void menu_estiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_estiloActionPerformed

        dialog_estilo.setVisible(true);
        dialog_estilo.pack();
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_estiloActionPerformed

    private void menu_colorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_colorTextoActionPerformed
        dialog_colorTxt.setVisible(true);
        dialog_colorTxt.pack();
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_colorTextoActionPerformed

    private void menu_colorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_colorFondoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_colorFondoActionPerformed

    private void menu_tamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tamanoActionPerformed
        /* JOptionPane tamano = new JOptionPane();
        tamano.showInputDialog("ingrese el tamano");
        int size = Integer.parseInt((String) tamano.getInputValue());
        Font fuenteVieja = jTextArea1.getFont();
        Font nuevaFuente = new Font(fuenteVieja.getFontName(), fuenteVieja.getStyle(), size);
        jTextArea1.setFont(nuevaFuente);*/

 /*    JOptionPane sz = new JOptionPane("ingrese el tamano");
        sz.show();
        int tam = Integer.parseInt((String) sz.getInputValue());
        Font vieja = jTextArea1.getFont();
        Font nueva = new Font(vieja.getFontName(), vieja.getStyle(), tam);
        jTextArea1.setFont(nueva);*/
        dialog_size.setVisible(true);
        dialog_size.pack();

        // TODO add your handling code here:
    }//GEN-LAST:event_menu_tamanoActionPerformed

    private void menu_tamanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_tamanoMouseClicked
        System.out.println("a");
        JOptionPane sz = new JOptionPane("ingrese el tamano");
        sz.show();
        int tam = Integer.parseInt((String) sz.getInputValue());
        Font vieja = jTextArea1.getFont();
        Font nueva = new Font(vieja.getFontName(), vieja.getStyle(), tam);
        jTextArea1.setFont(nueva);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_tamanoMouseClicked

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

        int size = Integer.parseInt(txt_size.getText());
        Font fuenteVieja = txt_size.getFont();
        Font nuevaFuente = new Font(fuenteVieja.getFontName(), fuenteVieja.getStyle(), size);
        jTextArea1.setFont(nuevaFuente);
        dialog_size.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void jcb_estiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_estiloActionPerformed

        int estilo = jcb_estilo.getSelectedIndex();
        Font fuenteVieja = jTextArea1.getFont();
        Font nuevaFuente = new Font(fuenteVieja.getFontName(), estilo, fuenteVieja.getSize());
        jTextArea1.setFont(nuevaFuente);
        dialog_estilo.show(false);
    }//GEN-LAST:event_jcb_estiloActionPerformed

    private void btn_colorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorTxtActionPerformed
        Color seleccionado = JColorChooser.showDialog(this, "Seleccione un color", Color.WHITE);
        jTextArea1.setForeground(seleccionado);
        dialog_colorTxt.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_colorTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notepadPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notepadPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notepadPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notepadPlus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notepadPlus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem boton_nuevo;
    private javax.swing.JMenuItem boton_salir;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_colorTxt;
    private javax.swing.JDialog dialog_ColorFondo;
    private javax.swing.JDialog dialog_colorTxt;
    private javax.swing.JDialog dialog_estilo;
    private javax.swing.JDialog dialog_size;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcb_estilo;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenuItem menu_colorFondo;
    private javax.swing.JMenuItem menu_colorTexto;
    private javax.swing.JMenuItem menu_estilo;
    private javax.swing.JMenu menu_formato;
    private javax.swing.JMenuItem menu_fuente;
    private javax.swing.JMenuItem menu_tamano;
    private javax.swing.JTextField txt_size;
    // End of variables declaration//GEN-END:variables
}
